version: '3.9'
services:
  "novo-boleto-app-0504":
    image: novo-boleto-app-0504
    container_name: novo-boleto-app-0504
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - ${APP_INGRESS_SERVER_PORT:-8080}:8080
    build: .
    healthcheck:
      test: curl http://localhost:8080
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 10s
    networks:
      - app-novo-boleto-app-0504
networks:
  app-novo-boleto-app-0504:
    driver: bridge

