version: '3.9'
services:
  "boletos-app":
    image: boletos-app
    container_name: boletos-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - ${APP_INGRESS_SERVER_PORT:-8080}:8080
    build: .
    healthcheck:
      test: curl http://localhost:8080
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 10s
    networks:
      - app-boletos-app
networks:
  app-boletos-app:
    driver: bridge

