##
# Spring - default profile
##
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: copom-comunicados-app

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
      base-path: /

##
# Open Feign
##
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
